# Generated by Django 4.1.5 on 2023-03-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedpassword',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
